### ISSUE TITLE
No message notifications between iOS devices. after the update from 20.8 to 21.0 

### ISSUE THREAD

**Issue by chosebine501** [nextcloud/talk-ios#524]
Hi,
since a week, I was trying to update to 21.0
and each time the notifications don't work between the IOS.
I took a snapshot of my server, I put Nextcloud server up to date at 21.0 successfully. And the notifications stop working, I do a reverse snapshot and all working again.
[(nextcloud/talk-ios#508)](https://github.com/nextcloud/talk-ios/issues/508)

Regards.

**Comment by SystemKeeper** [comment]
@chosebine501 v11.0.1 is now available in the App Store, this should fix the notification problems you’re seeing.

**Comment by chosebine501** [comment]
Hi,

I installed, and it's works perfectly !
great job!
thank you
regards

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Ho551** [comment]
Hello!
Apparently there is still a problem.
If an account is used on several devices, sporadically no notification appears.
Latest version is installed.
Can someone recreate that?

**Comment by SystemKeeper** [comment]
Did not see this at my end @Ho551 . Can you give us some details ? Are all devices talk-iOS devices or are there web sessions as well? Are all devices at 11.0.1? Just chat notifications or calls as well? Any way to reproduce it ?

As soon as there is any session still open, no notification will be send.

**Comment by Ho551** [comment]
@SystemKeeper In my case all devices running talk-iOS V11.0.1. 

When the error occurs, there is no active web session. With iOS devices, the app may not be completely closed (running in the background). Before Talk 11 there were no problems here. 
The session is probably not deactivated correctly after using the app.
The problem is with chat notifications and call notifications. In my case, the secondary device used did not receive a chat notification but received a call notification. The device that was primarily used received no notification at all.
The behavior always repeated when the user was inactive for about 5 minutes and the app was running in the background. 
As long as you do not open the app manually, you will not receive a notification.

**Comment by chosebine501** [comment]
Hello,
Yes, I have a person who has this problem, it's not every time, If she doesn't close talk completely for about 5 minute, she doesn't receive notifications, and even notifications from a caller.
but she had the same problem also before talk 11,
She device they are iphone8 with version (14.4) and one ipad mini 2 (12.5.1).

regards.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by SystemKeeper** [comment]
@Ho551 Thanks for the details, I‘ll try to reproduce this, but haven’t seen this myself yet.

> The device that was primarily used received no notification at all.

To be sure, in general notifications work at this device for talk-ios? So it depends on when the session of the second device expires ?

@chosebine501 This sounds like there is indeed an active session, but if this happened before talk 11 there might be something else going on.

Would it be possible for any of you to temporarily disable the second device and make sure it works / doesn’t work correctly with only one device ?

**Comment by Ho551** [comment]
@SystemKeeper I have now uninstalled Talk on the second device.
The problem persists. I can't really narrow it down to one possible cause yet. However, the behavior remains the same. After a few minutes of inactivity, no notifications will be displayed.

Have you been able to reproduce the problem?

**Comment by Ho551** [comment]
@SystemKeeper is there any new information? Do you need more details?

**Comment by chosebine501** [comment]
We have more tests in the last few weeks
To summarize:
1. the problem dates from to version 11.0
2. the problem is only present when there are two Talk on two IOS, connected with the same account.
3. to get around the problem, the person has to close Talk completely at the end of each use, on both IOS.

regards

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Ho551** [comment]
@chosebine501 In my case, Talk was uninstalled on the second device. But the behavior is the same as you describe it.

**Comment by chosebine501** [comment]
Out of my 12 people who use my system, only one has two IOS and has this problem.
And if you disconnect one of these IOS all goes back to normal.
All the others are working fine.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by chosebine501** [comment]
So if you have a central firewall.
I noticed one thing, since IOS 14.2
I had to open the port 5223 tcp to apple IP.
Why? I don't know....
probably for our safety :)

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Ho551** [comment]
@SystemKeeper @Ivansss can you reopen the case? The problem is still there for me. Even after the last update of Talk and Talk iOS, there still seems to be a problem with the session. Sometimes no notifications are displayed.

**Comment by Ivansss** [comment]
Hi @Ho551 :)

We can keep investigating this issue.
It would be nice if we could find a pattern to reproduce the issue because unfortunately I'm not able to reproduce it in any of my devices.

Does it only happens when you leave the app running in the background?
Do you send the app to the background while in a chat?

Any information that could help us to identify the issue is welcome.

**Comment by Ho551** [comment]
Hi @Ivansss :)

Thank you for your message.
The problem mostly occurs when Talk is moved to the background while the chat is active (selected). After a while, notifications will no longer appear until the app is reactivated. I haven't been able to find an exact pattern either.
Maybe this information will help

**Comment by e-caste** [comment]
Hi everyone 👋 
I'm also experiencing this same issue on 3 different iOS devices, 2 iPhones and an iPad (all on iOS 14), and different Nextcloud accounts. I don't know if this issue has been introduces with Talk 11, Nextcloud 21, or a combination of both, but notifications are unpredictable. I use this app every day and it's just that sometimes I get a notification, sometimes I don't. I couldn't find a pattern, since the missing notification issue presents itself both when the app has been just recently sent to the background or closed, and when the app has not been opened in a few hours.
I hope there will soon be a fix for this, let me know if I can test anything to help.

EDIT: this seems to be fixed on my end as of 11.1.1

**Comment by lotofbits** [comment]
Push notifications still do not work reliably

Hi :),
even after the latest update of the IOS app to 11.1.1, push notifications are unfortunately not always played out. Only when mentioned with @, the push notifications are reliably displayed. Unfortunately, I have not yet been able to identify a concrete pattern of when delivery does not take place. 

Talk-ios: 11.1.1
Talk on the server: 11.1.2
Nextcloud server: 21.0.0

**Comment by jjaiso** [comment]
Hello,

I am having this issue as well.  I have uninstalled, and re-installed the app, ensured I wasn't in a Talk session in my browser, I logged out of my NC session in my browser, but no notifications come through at all.

I have tried keeping the Talk iOS app in the background and received zero notifications.  I tested with closing the Talk iOS app and issue persists.

Talk-iOS: 11.1.1
NextCloud Talk App: 10.0.7
NextCloud Server: 20.0.9

Thanks,

**Comment by Ho551** [comment]
Hello @Ivansss! 
After the last updates, the chat notifications seem to reappear, but the call notification no longer appears.
No pattern can be seen here either.

Talk-iOS: 11.1.3
NextCloud Talk App: 11.2.1
NextCloud Server: 21.0.1

Thanks!
